name: ruff and mypy

on:
  pull_request:
    branches: [ main ]
jobs:
  codestyle:
    runs-on: ubuntu-latest
    environment:
      name: CI

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python3 -m pip install uv
        uv sync --frozen
    - name: Linting and static code checks
      run: |
        uv run pre-commit run --all
        
